pipeline {
    agent any

    environment {
        REGISTRY = "localhost:5001"
        IMAGE = "${REGISTRY}/calculator:exercise9"
        HAZELCAST_IMAGE = "hazelcast/hazelcast:3.12"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'feature', url: 'https://github.com/brandweis/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition'
            }
        }

        stage('Build JAR') {
            steps {
                sh './gradlew clean build -x test'
            }
        }

        stage('Build Image') {
            steps {
                sh 'docker build -t $IMAGE .'
                sh 'docker push $IMAGE'
            }
        }

        stage('Test Calculator /div Endpoint') {
            steps {
                script {
                    sh 'docker network create jenkins-test || true'

                    sh 'docker run -d --rm --name hazelcast --network jenkins-test $HAZELCAST_IMAGE'
                    sh '''
                        docker run -d --rm --name calculator --network jenkins-test \
                        -p 5002:8080 $IMAGE
                    '''
                    sleep time: 5, unit: 'SECONDS'
                    sh 'curl http://localhost:5002/div?a=10&b=2'
                }
            }
        }
    }

    post {
        always {
            sh 'docker stop hazelcast || true'
            sh 'docker stop calculator || true'
        }
    }
}

