pipeline {

  agent {
    label 'week11'
  }

  triggers {
    pollSCM('* * * * *')
  }

  environment {
    IMAGE_VERSION = "${BUILD_TIMESTAMP}"
    IMAGE_NAME = "branweis/calculator:${IMAGE_VERSION}"
    LOCAL_IMAGE = "localhost:5000/brandweis/calculator:${IMAGE_VERSION}"
  }

  stages {

    stage("Checkout") {
      steps {
        git url: 'https://github.com/brandweis/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git',
            branch: 'staging-environment'
      }
    }

    stage("Docker Build & Push") {
      steps {
        script {
          sh 'docker build -t $IMAGE_NAME Chapter08/sample1'
          sh 'docker tag $IMAGE_NAME $LOCAL_IMAGE'
          sh 'docker push $LOCAL_IMAGE'
        }

        withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          sh '''
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME
          '''
        }
      }
    }

    stage("Update version") {
      steps {
        sh 'cd Chapter08/sample1 && sed -i "s/{{VERSION}}/${IMAGE_VERSION}/g" calculator.yaml'
      }
    }

    stage("Deploy to staging (local)") {
      steps {
        sh '''
          kubectl config use-context docker-desktop
          kubectl --insecure-skip-tls-verify apply -f Chapter08/sample1/hazelcast.yaml
          kubectl --insecure-skip-tls-verify apply -f Chapter08/sample1/calculator.yaml
        '''
      }
    }

    stage("Deploy to release (GKE)") {
      steps {
        sh '''
          kubectl config use-context gke_ex11-456820_us-east1_hello-cluster
          kubectl --insecure-skip-tls-verify apply -f Chapter08/sample1/hazelcast.yaml
          kubectl --insecure-skip-tls-verify apply -f Chapter08/sample1/calculator.yaml
        '''
      }
    }

  }
}

