apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
  namespace: prometheus
type: Opaque
stringData:
  apiURL: https://hooks.slack.com/services/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

